### ISSUE TITLE
Excessive load. Low TPS and server crash.

### ISSUE THREAD

**Issue by Mr-Krab** [mekanism/Mekanism#5356]
#### Steps to reproduce:
1. Install the latest version of the mod.
2. Place logistic transporters and send many items through them.
3.??? Crash!

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2796
**Mekanism:** 1.12.2-9.6.9.367 

[crash-2019-04-08_07.20.06-server.txt](https://github.com/mekanism-mod/Mekanism/files/3052630/crash-2019-04-08_07.20.06-server.txt)

A few more seconds and I did not have time to do and save it.
![screen LagGoogles](https://user-images.githubusercontent.com/29023558/55699052-fbdf4700-59d9-11e9-9425-54ea96acf7fb.jpg)

Pipes
![screen2](https://user-images.githubusercontent.com/29023558/55699811-a3aa4400-59dd-11e9-96a7-dcda3c90ab9e.jpg)

**Comment by Mr-Krab** [comment]
Make a limit items in the pipes. TPS crashes when they overflow.
![screen](https://user-images.githubusercontent.com/29023558/55700139-2d0e4600-59df-11e9-8a42-eed671c4cb40.jpg)

**Comment by pupnewfster** [comment]
This is fixed in 9.7 anyways as we massively overhauled the performance of logistical transporters.

**Comment by thiakil** [comment]
Looking at where it failed, it may still crash if you put enough items through, since ExNihilo seems to traverse their recipe list each time, despite your screenshot showing that they're full, but we shall see

**Comment by Mr-Krab** [comment]
@BloodyMods

**Comment by pupnewfster** [comment]
At the very least the impact from our end should massively go down.

**Comment by pupnewfster** [comment]
Would be great if now that 9.7.0 is released you could confirm this is no longer an issue/the impact has gone down.

**Comment by Mr-Krab** [comment]
The problem is still relevant, although the load has become less. You need to make a limit on the volume of items inside the pipe.

**Comment by thiakil** [comment]
This is a strange one, their item handler seems suboptimal from a performance perspective as mentioned, and it does indeed seem to pass any pre-flight checks by the pipes, but when they actually try to insert it fails.

Seems to be an issue with creative bins too that they wont accept returning items lol

**Comment by pupnewfster** [comment]
Thinking about it maybe for low tier pipes (or more accurately low speed pipes), we should also partially include the logic we have for checking if there is room, except check it against the items that are already on route towards that destination. That way there would not be (or at least would be a lot less of a problem) where we send a lot of items to a destination when they won't actually be able to fit because we already sent enough to fill it up.

**Comment by pupnewfster** [comment]
Closing this as various issues have been fixed/improved on this and I have made even more improvements in the 1.15 branch in regards to logistical transporters.
