### ISSUE TITLE
Cables using their "default" variant.

### ISSUE THREAD

**Issue by Iwo-Witterel** [mekanism/Mekanism#5922]
Hello! I've encountered an issue while using this mod on my server. From time to time the cables seem to change their rotation and they all face upwards regardless of their position. Their texture looks like the one which appears when the item is in the player's hand. I don't know why this happens and it seems random. They are still working, but the issue is annoying.

Mekanism version: 1.15.2-9.9.11.403
Forge version: 31.1.18

![unknown2](https://user-images.githubusercontent.com/61750054/75797699-d1c31000-5d75-11ea-9f79-b0a426f067c8.png)

![unknown](https://user-images.githubusercontent.com/61750054/75797708-d4be0080-5d75-11ea-86d3-5cb545061a82.png)

**Comment by vongola12324** [comment]
Same issue here. And almost happened at the same time (as the time of this issue).

Mekanism version: 1.15.2-9.9.10.402
Forge version: 31.1.16

**Comment by jmgooden94** [comment]
+1

I've also noticed that the issue is generally resolved by destroying a segment of the cable, then replacing it, but only temporarily.

**Comment by aidancbrady** [comment]
Can anyone reproduce this in singleplayer, or does it seem to only occur on servers?

**Comment by aidancbrady** [comment]
If it would be possible for someone to provide a replication procedure it'll be much easier to track this down.

**Comment by Iwo-Witterel** [comment]
I will try to reproduce this on singleplayer and will provide the info asap.

**Comment by Iwo-Witterel** [comment]
We've been trying to replicate this on singleplayer for the past 15 minutes but to no avail. It still may be possible on singleplayer but if that's the case it is very rare. On the other hand it happens quite often on multiplayer. It really seems random. My friends say, that it happens when you place some blocks near it, or if you place or destroy a cable. It even happened when none of us where doing anything that was directly connnected to the bugged cables. If we spot something on our server I'll write it here.

**Comment by aidancbrady** [comment]
Interesting. Even if it’s just reproducible on a server, a rough reproduction procedure could really help. I wasn’t able to get it to happen in my own server testing, although I didn’t try breaking or placing adjacent cables very much like you mentioned.

**Comment by Iwo-Witterel** [comment]
We've got other mods installed alongside with Mekanism but I doubt that they cause any interference. We use only Mekanism and Mekanism Generators from the Mekanism family. One guy on a discord channel suggested that this happened to him when he quickly entered previously unloaded chunks.

**Comment by aidancbrady** [comment]
Question- to fix the issue, am I correct that you can simply break and/or replace a cable and they will go back to normal? Also, is it only cables connected to the modified network or all cables in view?

**Comment by jmgooden94** [comment]
In my experience, breaking and replacing a cable temporarily fixes it, but since the issue occurs intermittently, it will go back to the "default" state. This temporary fix only affects those on the modified section of cable in my experience, not the entire network or all cables or all cables in view.

**Comment by jmgooden94** [comment]
The suggestion that it happens when transitioning into an unloaded chunk seems likely. If the issue is tied to state being out of sync between server and client that would also explain why it hasn't been reproducible in single player.

**Comment by aidancbrady** [comment]
By modified ‘section’ of cable, I’m guessing you mean all cables connected to the cable modified? So if you have 5 connected cables and they’re visually broken, breaking and replacing one will temporarily make them all function properly again?

I noticed that despite the transmitter not rendering properly, the contents seem to continue rendering. That’s strange, as it means the client is still getting the sync packets from the server.

**Comment by Iwo-Witterel** [comment]
One of my friend says that sometimes when he fixes one set of cables, other gets bugged, but he also states that it is not a rule and he doesn't know whether it causes it.

**Comment by aidancbrady** [comment]
Really appreciate the insights, all of these are really helpful. If you notice anything else interesting please let us know. I'm making this my priority over the next couple days, hopefully we can get it figured out.

**Comment by Iwo-Witterel** [comment]
You're welcome. The mod is awesome and definitely worth developing so if we can help we are happy to do that. We found some new behaviours about the bug, I will upload some photos with explanations in a few minutes.

**Comment by Iwo-Witterel** [comment]
![cables1](https://user-images.githubusercontent.com/61750054/75926694-4330ba80-5e6b-11ea-845f-924714377c1e.png)
![cables2](https://user-images.githubusercontent.com/61750054/75926701-4461e780-5e6b-11ea-89ff-a90049055b68.png)

Sometimes when this happens it also shows that the cable is not transporting anything. After breaking and placing again one cable it goes back to normal. It functions properly despite not displaying any energy going through the cables.

**Comment by Iwo-Witterel** [comment]
![cables one perspective](https://user-images.githubusercontent.com/61750054/75926802-74a98600-5e6b-11ea-9f09-02d2df64d9b2.png)
![cables second perspective](https://user-images.githubusercontent.com/61750054/75926811-78d5a380-5e6b-11ea-9971-b96ef506a0ef.png)

Here are two perspectives of the same cable. Sometimes just the content of the cable is not shown properly.

**Comment by Iwo-Witterel** [comment]
![cables before rejoin](https://user-images.githubusercontent.com/61750054/75926930-a4588e00-5e6b-11ea-99cb-f313064e8192.png)
![cables after rejoin](https://user-images.githubusercontent.com/61750054/75926933-a589bb00-5e6b-11ea-98da-eecf932009ee.png)

We found out that sometimes when one player rejoins the game it fixes the issue for the other players.

**Comment by Iwo-Witterel** [comment]
All of the above happened after teleporting to that place from other far away place. I might be wrong but I suspect that even alt-tabbing from the game can cause this issue sometimes.

**Comment by aidancbrady** [comment]
I notice that in your recent screenshots it appears that the bugged models are oriented laterally rather than vertically. Makes me think this is a model caching issue. Do the same cables screw up in the same way each time you teleport back from far away?

**Comment by Iwo-Witterel** [comment]
It doesn't happen everytime we teleport, just sometimes. And yes, they always end up the same as on the screenshots provided. Vertically placed cables seem to be alright, but when they change direction from vertical to horizontal it shows that they are in the "default" state too I think.

**Comment by Iwo-Witterel** [comment]
![direction](https://user-images.githubusercontent.com/61750054/75928110-fdc1bc80-5e6d-11ea-87d9-da9c7a939bc0.png)

Here they change direction but are still in the "default" state. So I think that the vertical/horizontal rotation doesn't matter. It just ignores the rotation and gives them wrong state.

**Comment by aidancbrady** [comment]
@pupnewfster has committed two changes which should *hopefully* fix this issue. One was actually a packet range calculation mistake which would cause the networks to not sync to the client. I'm marking this as 'fixed in dev,' but we won't close it until you test the new build and don't experience any problems. Hopefully we'll have a new release out soon.

**Comment by aidancbrady** [comment]
We've pushed Mekanism 9.9.15 to Curse with the mentioned changes. I'll leave this open to give y'all time to test it out. Let me know if you still encounter the same problems; if not, we'll call it fixed 😄

**Comment by jmgooden94** [comment]
Still able to reproduce, unfortunately. I was again able to temporarily fix it by destroying and replacing a segment of cable, but I teleported out and back in to the chunk and they all reverted to their vertical state again.

I'll reiterate what Iwo-Witterel said - seems cables are semi-randomly falling back to their vertical state, but still function normally. 

I actually have not seen the issue they observed though where the cables appear empty; every time the issue has happened to my group, it has been like the first screenshot, where the energy/liquid/gas/items are still flowing, but the cable orientation is vertical.

**Comment by aidancbrady** [comment]
Sad :(

Just to be sure, both your client and the server are using the latest version, correct?

**Comment by jmgooden94** [comment]
Yeah, I did update both. An interesting sidenote that I just observed though is that the issue now seems to be localized to a smaller area when teleporting in/out of the chunk. Haven't been able to determine if that's a rule or a fluke yet, but it looks like just the chunk I teleported to is broken and the rest is fine.

**Comment by jmgooden94** [comment]
Tried to reproduce a few more times, and the chunk boundary seemed to be a fluke. Subsequent attempts seemed to just affect random sections of cable. I do think the issue is occurring less frequently now, but that could be due to other factors (less load on the server, since I'm just teleporting back and forth as opposed to actually building/playing).

I think your suspicion about caching is probably spot on, considering that the issue happens pretty randomly and seems most likely to happen when loading/unloading chunks.

**Comment by aidancbrady** [comment]
I've pushed a somewhat inelegant fix which hopefully will solve these problems. It'll be ready for you to test soon.

**Comment by Iwo-Witterel** [comment]
We've updated the Mekanism version to the newest and the issue still persists :(

**Comment by pupnewfster** [comment]
This should be fixed in 9.9.16, which is now up and on curseforge. If not please comment and we can re-open it (though we will be entirely out of ideas of how to potentially fix it if it is still broken)

**Comment by jmgooden94** [comment]
Unfortunately still seeing the issue on random sections of cable. It now seems to sometimes resolve on its own, sometimes resolve when you destroy/replace a section of cable, and sometimes doesn't happen.

![2020-03-15_20 12 25](https://user-images.githubusercontent.com/10620307/76720191-58bea380-66f9-11ea-9776-6b41324f0840.png)

**Comment by pupnewfster** [comment]
Out of curiosity is that a chunk border where that image shows them being still broken?

**Comment by EnterFor** [comment]
Does it depend on the version of Java being used?
May I ask about your Java version?
I'm still using Java8

**Comment by jmgooden94** [comment]
Sorry @pupnewfster haven't had a chance to play since then, so I'm not sure if it was a chunk border, but I don't think so...

We are also using Java8.

**Comment by pupnewfster** [comment]
Should be fixed in 9.9.18, apparently accidentally referenced it from the commit in a way that closed the issue even though it is not released yet.

**Comment by aidancbrady** [comment]
v9.9.18 is released, please let us know if you encounter the issue again!

**Comment by ocram9** [comment]
Bad news, it still doesn't seem to be fixed. I just updated to 9.9.18, and the cables still go back to their vertical state. I replaced the cable (which fixed it), unloaded the chunk by flying away and then flew back. When I got back the cables were vertical again

![2020-04-06_01 15 24](https://user-images.githubusercontent.com/49008532/78512430-aed8b100-77a4-11ea-8730-fb18c947c6c8.png)

**Comment by pupnewfster** [comment]
Can you please provide a list of mods in the pack.

**Comment by ocram9** [comment]
I'm not playing in a pack, I've manually downloaded these mods (not sure if that is usefull info but still). 
I have also tried to create a new server with just mekanism and see if the issue is there too but I haven't been able to recreate it (so it might be a mod conflict after all). I'm not sure what is causing it on my main server either so I can't be sure of that. Anyway here are the mods:

AI improvements-1.15.2-0.3.0.jar
AppleSkin-mc1.15.2—forge-1.0.13.jar
Aquaculture-1.15.2-2.0.13.jar
AutoRegLib-1.5—40.jar
BiomesOPlenty-1.15.2-10.0.0.353-univers...
BooksheIf-1.15.2-5.3.10.jar
BotanyPots-1.15.2-2.0.6.jar
caelus-FORGE-1.15.2-2.0-beta1.jar
cfm-7.0.0-pre16-mc1.15.1.jar
chunkt-1.15.2-1.0.2.jar
CIickMachine-1.15.2-3.0.2.jar
CookingForBlockheads_1.15.2-8.0.1.jar
craftingstation-3.1.0.jar
Cucumber-1.1S.2-3.0.4.jar
curios-FORGE-1.15.2—2.0.2.jar
curiouselytra-FORGE-1.15.2-2.0.jar
dcintegration-1.1.14-1.15.jar
DimStorage-1.15.2-3.1.0.jar
DoggyTalents—1.15.2—1.15.2.3.jar
engineersdecor-1.15.2-1.0.20-b4.jar
extlights—2.0.jar
extratags-1.0.jar
FarmingForBlockheads_1.15.2-6.1.0.jar
FastLeafDecay-v20.Jar
fI-3.1.6.jar
flux-4.12.4.jar
Hwyla-forge-1.10.8-B72_1.15.2
Immersive-portals-0.11
Industrial+Agriculture[Core]
industrial+Agriculture[Mekanism]
inftrading_1.15.2-1.0.jar
invtweaks-1.15.2-1.0.3.jar
JAOPCA-1.15.2-3.2.0.8.jar
jei-1.15.2-6.0.0.2.jar
journeymap-1.15.2—5.7.0beta1.jar
Lollipop-1.15.2-1.0.13.jar
mcw-furniture-1.0.1-mc1.15.1+1.15.2.jar
Mekanism-1.15.2-9.9.18.410.jar
MekanismGenerators-1.15.2-9.9.18.410.jar
minecolonies-O.11.812-ALPHA-universalj...
MixinBootstrap-1.0.2.jar
MouseTweaks-2.13-mc1.15.1.jar
music_p|ayer-1.15.2-2.0.13.64.jar
MysticalAgriculture-1.15.2-3.0.1.jar
obfuscate-0.4.1-1.15.2.jar
openbackup-1.15.1-0.0.0.2.jar
OreExcavation-1.7.151.jar
OverpoweredMending-1.15.2-2.0.0+11.jar
performant-1.15-1.12.jar
phosphor-forge-mc1.15.2-O.5.2+bui|d.4.jar
PIacebo-1.15.2-3.0.2.jar
Powah-1.15.2-1.1.11.jar
Quark-r2.1-229.jar
refinedstorage-1.8.1.jar
refinedstorageaddons-0.6.1.jar
rsgauges-1.15.2-1.2.2.jar
shutdowner-1.6.jar
simplefarming-1.15.2-1.2.7.jar
simplybackpacks-1.15.2—1.4.5.jar
simplylight-1.15.2-0.9.0.jar
speedyhoppers-1.15.2-2.jar
StorageDrawers-1.15.2-7.0.2.jar
structurize-0.10.293-ALPHAJar
thutcore-1.15.2-7.0.2.jar
thuttech-1.15.2-8.0.2.jar
titanium-1.15.2-2.3.6.jar
tombstone-4.3.3-1.15.2.jar
torchmaster-2.1.1-rc0.jar
u_team_core-1.15.2-2.11.0.156.jar
valkyrielib-1.15.2-3.0.2.1.jar
vehicle-mod-0.43.5.jar
worldedit-forge-mc1.15.2-7.1.0.jar
xercamusic-1.15.2-1.0.jar

**Comment by pupnewfster** [comment]
By pack I meant the group of mods you are playing (not necessarily a prebuilt pack). So thank you for the list. Are you able to reproduce this issue without Immersive Portals? Backup your world first so that removing the mod doesn't break your save as you can revert to it after testing.

**Comment by ocram9** [comment]
Removing immersive portals seems to have fixed it :) 
Is this fixable on your end or should I contact the immersive portal devs?

**Comment by pupnewfster** [comment]
Going to go ahead and close this issue then as I believe it is https://github.com/qouteall/ImmersivePortalsModForForge/issues/49 given based on their response in that issue, my guess is they are overriding forge's IModelData system.

**Comment by yoyotam3** [comment]
I'm still getting this issue in Enigmatica 6, which does not have Immersive Portals

**Comment by yoyotam3** [comment]
Actually it might be the TARDIS mod?
