### ISSUE TITLE
[1.15.2] Shift + N doesn't work in JEI when a recipe is selected

### ISSUE THREAD

**Issue by ocram9** [mekanism/Mekanism#6085]
#### Issue description:
When you want to check a description it doesn't open in JEI when you already have a recipe selected. The general info (just shift) does work.

#### Steps to reproduce:
1. Select a recipe in JEI
2. Try to check a description using shift+n on a supported mekanism item

#### Versions:
**Forge:** 31.1.47
**Mekanism:** 9.10.0
**Minecraft:** 1.15.2

**Comment by Yoosk** [comment]
Can confirm: https://yoosk.pl/wtc0mrHc.webm

**Comment by feteryeeter420** [comment]
i fixed this by going into controls and fixing the item descriptions and stuff. it works fine for me.

**Comment by ocram9** [comment]
> i fixed this by going into controls and fixing the item descriptions and stuff. it works fine for me.

I'm not sure what you mean. I tried different key bindings for the item description but the issue persists.
