### ISSUE TITLE
[1.16.1] Mekanism crash while booting client.

### ISSUE THREAD

**Issue by Gbergz** [mekanism/Mekanism#6286]
#### Issue description:
While trying to boot the game with all Mekanism mods, it crashes.

#### Steps to reproduce:
1. Install Mekanism + all other mekanism mods (incl. additions.)
2. Try to boot the game.
3. Crash.

#### Version:
**Forge:** 32.0.62
**Mekanism:** 10.0.0.423
**Other relevant version:** MC 1.16.1

#### If a (crash)log is relevant for this issue

https://hastebin.com/axekapamuk.rb

EDIT: Removing the specific mod Mekanism Generators solves this issue for whatever weird reason.

**Comment by pupnewfster** [comment]
Based on the same crash report we received on discord, in which I asked for the latest log (as the crash report doesn't contain any useful information due to https://github.com/MinecraftForge/MinecraftForge/issues/6374). I believe this issue will be fixed once https://github.com/MinecraftForge/MinecraftForge/pull/6951 gets merged into forge

**Comment by pupnewfster** [comment]
I believe this should be fixed once Forge `32.0.63` is released. I will leave this issue open though until we eventually update to 10.0.1 and bump the minimum version required to run mekanism to that. Note: Currently the forge jenkins choked (it often does that if it attempts to do multiple things at once), so the forge build is waiting until someone with the power has time to bump Jenkin's and have the build start again. If I remember when I notice that it actually has built I will leave another comment on this issue.

**Comment by pupnewfster** [comment]
Forge's jenkins got bumped so it should now work properly after you update forge.

**Comment by Oriana-Anima** [comment]
Same issue here, not fixed.

**Version:**

**Forge:** 32.0.63
**Mekanism:** 10.0.0.423
**Other relevant version:** MC 1.16.1

**If a (crash)log is relevant for this issue**

https://hastebin.com/kitiyotaze.php

**Comment by Gbergz** [comment]
Works properly now, thank you!
- Gbergz
