### ISSUE TITLE
Blocks from Mekanism Generators don't have culling at all

### ISSUE THREAD

**Issue by TheAirBlow** [mekanism/Mekanism#7669]
### Issue description

Blocks from Mekanism Generators like Valves and etc. don't have culling, therefore causing a lot of lag in big multiblocks, like the Industrial Turbine.

### Steps to reproduce

Build an Industrial Turbine 11x18x11, go into spectator and noclip into the turbine's blocks

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

14.23.5.2860

### Mekanism version

Older

### Other relevant versions

None

**Comment by TheAirBlow** [comment]
I think the problem is that generators and blocks for multiblocks use the same block ID, and because generators must have culling disabled the blocks also have culling disabled.

**Comment by pupnewfster** [comment]
Fixed in 10.3.4

**Comment by TheAirBlow** [comment]
> Fixed in 10.3.4

Well yeah, the problem is that it is not fixed on 1.12.2. Oh well, the probability of it being fixed is close to zero.

**Comment by pupnewfster** [comment]
Mekanism for 1.12 is no longer being developed
